name: Deploy to My Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload project files to Windows server
        uses: garygrossgarten/github-action-scp@v1.1.0
        with:
          local: .
          remote: ${{ secrets.SERVER_PATH }}
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}

      - name: Build & Restart app on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            npm install
            npm run build
            pm2 delete n-website || true
            pm2 start "npm run start" --name n-website
            pm2 save


